## svn $Id: xir3000.conf.R 655 2010-10-05 19:02:42Z john $
##                                                         
##  Configuration for XIR3000 plugin.
##  Read data from Russell Technologies' XIR 3000 USB
##  radar video processor.
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  

## is this plugin currently enabled when loaded?

enabled = TRUE 

## The following flag says that this plugin is enabled whenever
## it is loaded.  TRUE here makes the "enabled" parameter redundant.

always.enabled = TRUE

## Path to the RTI client library; user will be prompted if library is not found
## here.  Currently, this plugin supports only version 1.5.0.012 of the RTI SDK,
## and we redistribute the minimal required subset of these files with the kind
## permission of Harvey Russell of RTI.

client.lib = "plugins/xir3000/SDK/CANRib.dll"

## Name of antenna configuration to use.  This is one of the
## names from the RTI database (CANStar.ant) whose records
## are available in the Misc/Antenna DB/ subfolder of the
## RTI SDK folder (for users who have purchased the SDK).
## Users needing to use antennas not already in the database
## may contact the author of radR to have their antenna added
## to the database.

antenna = "Decca BridgeMaster E"

## Most digitizing parameters are stored in an RTI database (CANStar.ant),
## but the following are not:

## pulses to capture per sweep

pulses = 4096

## sample rate, in MHz (must be 27, 54, or 100)

sample.rate = 100

## timeout for opening an XIR3000 USB device, in seconds

timeout = 10
