## svn $Id: multiframecorr.conf.R 574 2010-05-11 02:07:15Z john $
##
##  MULTIFRAMECORR TRACKER MODEL CONFIG
##
##  These are parameters for the multiframe
##  tracker model.
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it may be overwritten with new values when you exit
##  radR.
##
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.
##

## number of frames over which to "backtrack" in building
## tracks

k = 2

## relative weighting of directional coherence in gain
## function (the other component of gain, which receives
## 1 - alpha as weight, is relative proximity to predicted
## location)

alpha = 0.5

## a small penalty added to the gain function for any
## edge connecting blips in non-consecutive scans; this
## is meant to prevent exclusion of blips from perfectly
## straight-line tracks.  This is in gain units, not log units.

eps = 1e-3

## the minimum gain (between 0 and 1) required for a blip
## to be considered for joining a track
## The value of 0.9090909090909 corresponds to "10" in log units.

min.gain = 0.9090909090909
