## svn $Id: nearestneighbour.conf.R 266 2009-03-04 21:41:04Z john $
##
##  NEARESTNEIGHBOUR TRACKER MODEL CONFIG
##
##  These are parameters for the nearestneighbour
##  tracker model.
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it may be overwritten with new values when you exit
##  radR.
##
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.
##

## time (seconds) for which a new lone blip is considered
## "fresh" (i.e. eligible for starting a track)

blip.fresh.time = 3

## time (seconds) elapsed after last added blip when a track is
## declared "stale" (i.e. finished and no longer eligible for extension)

track.stale.time = 10

## We don't extend tracks using blips that would cause too large
## a turning angle, or too high a percentage change (up or down)
## in area or intensity between consecutive blips along the track

## maximum turning rate, in degrees per second:

max.turn.rate = 20

## maximum area change, in percent per second:

max.area.change.rate = 150

## maximum mean intensity change, in percent per second:

max.int.change.rate = 150
