## svn $Id: tracker.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##  TRACKER  PLUGIN  CONFIG
##                                                         
##  These are parameters for the radR plugin tracker       
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## Is this plugin enabled upon loading?

enabled = TRUE

## where blips are saved, by default; this can include a path
## It is a basename:  extensions will be added to it.

track.filename = "mytracks" 

## file extensions (added to the basename):

scanfile.ext = ".scans" 
blipfile.ext = ".blips" 
trackfile.ext = ".tracks" 

## default name of a .CSV file to which complete tracks
## are written

csv.filename = "tracks.csv" 

## are tracks written to the .CSV file?

save.to.csv = TRUE 

## the date/time format to use for the CSV track output
## file.  This must include the date and time formats
## separated by a comma, in order to be consistent
## with what this plugin outputs for each blip.

date.time.format = "%Y/%m/%d,%H:%M:%S" 

## column names for the .CSV file (requires a "\n" at the end)
csv.file.header = "scan.no,track.no,blip.no,date,time,timestamp,range,x,y,z,ns,area,int,max,aspan,rspan,perim\n" 

## a function to format a track.  It takes two arguments:
## - track: a data frame with rownames equal to blip numbers and columns as in RSS$patches
## - index: the absolute track index among all tracks processed
## This function must return a 1-element character vector which is
## output to the .CSV file.  Presumably, it has embedded commas and
## newline characters so that it looks like columns matching those named
## in csv.file.header
## The final trailing "\n" should be omitted.

format.track.for.csv = function(track, index) {
  paste(sprintf("%d,%d,%d,%s,%.3f,%.0f,%.0f,%.0f,%.0f,%d,%.0f,%.3f,%.3f,%d,%d,%.0f",
                track$scan,
                index,
                as.integer(rownames(track)),
                format(structure(track$t, class="POSIXct"),
                       format=date.time.format, tz=RSS$timezone),
                track$t,
                track$range,
                track$x,
                track$y,
                track$z,
                track$ns,
                track$area,
                track$int,
                track$max,
                track$aspan,
                track$rspan,
                track$perim),
        collapse="\n")
} 

## should plotted tracks be smoothed?  Doesn't affect
## data stored, only display.

smooth.plotted.tracks = FALSE 

## Maximum allowed speed of an object (km/h).
## Blips whose positions in time and space imply a speed
## between them larger than this are not joined into
## the same track.

track.max.speed = 100 

## length of time for which a complete track is retained for
## display

retain.complete.tracks.for = 300

## minimum number of blips in a track for it to be saved

track.min.blips = 4 

## colour of a track in each possible state
## These must appear in the same order as the TS.XXX constants
## in tracker.plugin.R, i.e.:
##       TS.NASCENT              = 1
##       TS.ACTIVE               = 2
##       TS.COMPLETE             = 3
##       TS.COMPLETED.IN.PREVIEW = 4
##       TS.DISCARDED            = 5
##       TS.SELECTED             = 6

track.colour = c("#ff8100", "#ff8100", "#906048", "#c87024", "#ff0000", "#ffffff") 

## minimum number of blips in a track for it to be displayed

min.blips.to.show = 2

## format for popup window time

time.format = "%H:%M:%S" 

## function to format track summary info for the popup window
## state is one of the TS.XXX values from tracker.plugin.R
## length is in metres; times in seconds

format.for.popup = function(index, rel.index, state, num.points, length, start.time, end.time) {
  sprintf("%s track with %d points\n#%d in all.tracks%s\nFrom %s to %s\nLength: %.0f m   Mean Speed: %.1f km/h\n-------------------------------------",
          state.names[state],
          num.points,
          index,
          if (state == TS.COMPLETE) "" else "; #" %:% rel.index %:% " in tracks",
          format(start.time, time.format, tz=RSS$timezone),
          format(end.time, time.format, tz=RSS$timezone),
          length,
          length / (end.time - start.time) * 3.6 )
} 

## function to format track summary info for the popup window
## state is one of the TS.XXX values from tracker.plugin.R
## length is in metres; times in seconds

format.for.clipboard = function(index, rel.index, state, num.points, length, start.time, end.time) {
  sprintf("%d,%d,%s,%s,%.0f,%.1f",
          state,
          num.points,
          format(start.time, time.format, tz=RSS$timezone),
          format(end.time, time.format, tz=RSS$timezone),
          length,
          length / (end.time - start.time) * 3.6 )
} 

## format full track info for the console
## track is a list with item "points" giving indexes of the
## tracks' blips in the all.blips bigframe

format.full.for.console = function(track) {
  paste(state.names[if (is.null(track$state)) TS.COMPLETE else track$state],
        " track:\n", 
        paste(capture.output(all.blips[track$points,]), collapse="\n"),
        sep="")
} 

## format full track info for the clipboard
## track is a list with item "points" giving indexes of the
## tracks' blips in the all.blips bigframe

format.full.for.clipboard = function(track) {
  paste(if (is.null(track$state)) state.names[TS.COMPLETE] else state.names[track$state],
        " track:\n", 
        paste(capture.output(all.blips[track$points,]), collapse=GUI$clipboard.element.separator),
        sep="")
} 

## the list of paths along which to search for tracker models

tracker.model.pathlist = "./plugins/tracker" 

## name of the current model

current.model = "multiframecorr" 

## do we handle ending of expired tracks or does the model do it?
## this must be the appropriate value for the model named by
## current.model

auto.expire.tracks = FALSE 

## variable name to which a track's point coordinates are assigned when
## the mousebutton is clicked on it; NULL means none

gui.track.var = "tr" 

## variable name to which an active track's full details are assigned when
## the mousebutton is clicked on it

gui.track.obj.var = "to" 

## radius of circles to plot (at default zoom) around points of a selected track

circle.radius = 2 

## colours of circles to plot (at default zoom) around points of a selected track

circle.colour = list (
  normal = "orange",
  highlighted = "white",
  selected = "white"
  ) 

## shape of symbol to draw at the first pixel of a nascent track
## this is a vector of coordinates offsets (in pixels): X1, Y1,
## X2, Y2, ... Xn, Yn.  If the first (and only) point in a nascent
## track is at plot coordinates X, Y, a polygon is drawn with
## points at (X+X1, Y+Y1), (X+X2, Y+Y2), ... (X+Xn, Y+Yn)

nascent.track.symbol = c(-8, 0, 0, 8, 8, 0, 0, -8, -8, 0)

