## svn $Id$
##                                                        
##     ZONE SPECIFICATION FILE
##                                                        
##  These are parameters describing exclusion and special zones.
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it may be overwritten with new values when you quit radR.
##                                                        
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.            
##                                                        
##  Make sure to include a comma at the end of each item  
##  in a list, except the last.                           
##                                                        
##  NOTE:  all elements of lists must be given names      
##         e.g.   list(x=1, b=2) instead of list(1, 2)    
##                                                        
##

## Description (for humans) of what zones this file defines.

desc = "Default zone.  You can use the zone plugin to customize this."

## The list of defined zones.  Tags can be any words, but "exclusion" is treated
## specially to mean a zone where radR should not look for targets.
## Each zone is a list with items as shown below:

zones = list (

  exclusion = list (

    ## is this zone enabled?
    enabled = FALSE,

    ## is this zone visible?
    visible = TRUE,

    ## the colour for the zone outline
    colour = "#ff0000",
    
    ## A region is a union of segments, each of which is described by
    ## inner and outer radii, an angle, and an angular extent.  The
    ## segment is treated as extending between the two radii and from
    ## the angle clockwise for the number of degrees given by the
    ## extent.

    ## The default zone has just one segment, so the following items
    ## are vectors of length one.
    
    ## the inner and outer radii for segments (in metres)
    
    r = list (
      r1 = 0,
      r2 = 550
      ),

    ## the first and second angles for segments (in degrees clockwise from North)
    ## Note that for extent, 0 and 360 have different meanings.
    
    a = list (
      start = 0,
      extent = 360
      )
    )
  )




