## This Makefile is called recursively from the Makefile in the parent directory,
## and requires the variables defined there.

$(eval $(AT_MAKEFILE_START))
PLUGIN_EXTRA_R_FILES := video.windows.conf.R video.unix.conf.R
$(eval $(AT_MAKEFILE_END))
