## svn $Id: video.conf.R 794 2011-05-30 19:54:20Z john $
##                                                        
##     VIDEO   PLUGIN   CONFIG
##                                                        
##  Read frames from video files.
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it is overwritten with new values when you exit       
##  radR.                                                 


## is this plugin enabled?
enabled = TRUE

## this plugin is not always on
always.on = FALSE

## for guessing timestamps from the base filename, we use a strptime-compatible
## format string:
date.guess.format = "%Y-%m-%d %H-%M-%S"

## in order to recognize the presence of a date in the base filename,
## we use a regular expression compatible with date.guess.format
date.guess.regexp = "((19)|20)[0-9][0-9]-[0-9]?[0-9]-[0-9]?[0-9] [0-9]?[0-9]-[0-9]?[0-9]-[0-9]?[0-9]"

## regardless of the video's frame rate, at what rate do we grab frames for processing in radR?
## this is in frames per second
default.frame.rate = 10

## regardless of the video's actual resolution, we can specify the width
## and height in pixels for the frames we analyze:
default.width = 320
default.height = 200
