## svn $Id: help.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##  HELP   PLUGIN  CONFIG##                                                         
##  These are parameters for the sample plugin "help"      
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## is the plugin enabled upon loading? 

enabled = TRUE

## this plugin is always on

always.on = TRUE

## what's available where to help with radR

## If a right hand side does not begin with a protocol (e.g. "http:" or "mailto:"),
## it is assumed to be a filename relative to the radR directory.

## NOTE: make sure to use single backquotes for the labels
## (i.e. the left-hand-sides of the equations)

web.resources = list (
  `Browse the radR Wiki` = "http://radr-project.org",
  `Visit the radR download site at Acadia University` = "http://discovery.acadiau.ca/radR",
  `Email John B. a question or bug report` = "mailto:jbrzusto@fastmail.fm",
  License = "LICENSE.TXT"
  )

