## This Makefile is called recursively from the Makefile in the parent directory,
## and requires the variables defined there.

$(eval $(AT_MAKEFILE_START))

PLUGIN_EXTRA_TARGETS = ocr$(SHLIB_SUFFIX)

$(eval $(AT_MAKEFILE_END))
