##     PNGARCH   PLUGIN   CONFIG
##                                                        
##  Read frames from PNG files.
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it is overwritten with new values when you exit       
##  radR.                                                 


## is this plugin enabled?
enabled = TRUE

## this plugin is not always on
always.on = FALSE

## get the sequence numbers from filenames
## For Benoit Gineste's frame grabber, the filenames look
## like this:
##  20140129_ARDA_4J1_0001.png
## with the _0001 representing the sequence number.
get.seqno = function(x) as.numeric(sapply(strsplit(basename(x), "[_.]"), function(i) i[4]))

## get the sprintf template string from a filename;
## this string can be used to generate the filename for
## the n'th scan like so:  sprintf(template, n)

get.template = function(x) {
  parts = strsplit(basename(x), "[_.]")[[1]]
  parts[4] = "%04d.png"
  parts = parts[1:4]
  return (file.path(dirname(x), paste(parts, collapse="_")))
}
  
## defaults for configuration items

default = list (
  
  ## for reading timestamps from the OCR'd video grab timestamp, we use
  ## a strptime-compatible format string:
  date.ocr.format = "%d.%m.%y %H:%M:%S",

  ## bit mask for extracting the timestamp from the radar image
  date.ocr.bitmask = 0x00ff0000,
  
  ## the location of the timestamp on the PNG image
  ## is given by x[tsbox.h, tsbox.v]
  tsbox.h = 1107:1278,
  tsbox.v = 1001:1020,
  
  ## The clipping region is the subframe of each PNG image which we retain
  ## as data.  If the image is read as x = readPNG("myfile.PNG", native=TRUE),
  ## then the retained portion is
  ##   x[clip.h[1]:clip.h[2], clip.v[1]:clip.v[2]]

  ## horizontal clipping region
  clip.h = c(1, 1000),

  ## vertical clipping region
  clip.v = c(100, 500),

  ## The origin and radius determine the clipping region.
  ## This is the adjustment in pixels from the left, pixels from the top,
  ## which must be made to align the PNG images with the radar plot origin.
  ## i.e. if the PNG images have the radar at image centre, then the value
  ## here should be origin = c(0, 0).  If the image is left of centre,
  ## the x value should be positive.  If the image is above centre, the
  ## y value should be should be positive.

  origin = c(112.5, -2),

  ## number of pixels from centre to maximum range.

  radius = 496,

  ## The maximum range shown on the radar image is usually in km

  max.range = 1.5,

  ## The implied scale, in metres per pixel is the ratio of max.range * 1000 / radius
  scale = 1000 * 1.5 / 496,
    
  ## default rotation of the coordinate system, in degrees clockwise.
  ## Normally, y increases bottom to top, and x increases left to right, but
  ## any rotation can be specified here.

  rotation = 0
  )

## In the future, we might support other file types here:

file.extensions = list(
  png = 'PNG - sequence of PNG images'
)

## the plot window date format:
plot.title.date.format           = "%Y %b %d %H:%M:%OS3"
