## svn $Id: saveblips.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##  SAVEBLIPS  PLUGIN  CONFIG
##                                                         
##  These are parameters for the radR plugin saveblips     
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## Is this plugin enabled upon loading?

enabled = FALSE 

## where blips are saved, by default; this can include a path

blip.filename = "blips.csv" 

## whether to pop-up a plot of all blips
## when the pause button is hit

plot.on.pause = FALSE

## whether to plot range rings

plot.range.rings = FALSE 

## column names for the .CSV file (requires a "\n" at the end)

file.header = "blip.no,date,time,timestamp,x,y,z,ns,area,int,max,aspan,rspan,perim\n" 

## the date/time format to use for the CSV track output
## file.  This must include the date and time formats
## separated by a comma, in order to be consistent
## with what this plugin outputs for each blip.

date.time.format = "%Y/%m/%d,%H:%M:%S" 

## a function to format a data.frame of blips for the .CSV file
## This matches the output format of TRACKER$format.track.for.csv,
## except that the track ID is ommitted.

format.blips = function(blips) {
  paste(sprintf("%d,%s,%.3f,%.0f,%.0f,%.0f,%d,%.0f,%.3f,%.3f,%d,%d,%.0f",
                RSS$total.num.blips + seq(along=blips$x),
                format(structure(blips$t, class="POSIXct"),
                       format=date.time.format, tz=RSS$timezone),
                blips$t,
                blips$x,
                blips$y,
                blips$z,
                blips$ns,
                blips$area,
                blips$int,
                blips$max,
                blips$aspan,
                blips$rspan,
                blips$perim),
        collapse="\n")
}
