## svn $Id: radR.conf.R 800 2011-06-18 15:03:25Z john $
##
##  RADR  CONFIGURATION  FILE
##
##  These are parameters for the radR base system,
##  not including user interface (see guiconf.R for that).
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.
##
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.
##
##  Make sure to include a comma at the end of each item
##  in a list, except the last.
##
##  NOTE:  all elements of lists must be given names
##         e.g.   list(x=1, b=2) instead of list(1, 2)
##

## What timezone to use for date displays:
timezone = "GMT"

## Noise cutoff: any samples less than the following value (in sample
## units) are treated as noise and set to 0.  This value should be
## determined from the calibration mapping between received signal dbm
## and sample value.

noise.cutoff = 0

## Are we finding blips in scans?

blip.finding = TRUE

## Are we filtering blips in scans?

blip.filtering = TRUE

## When processing data from a new source (i.e. starting to play a new
## tape segment, or going live), no sample classification or blip
## extraction takes place for a certain number of scans, so that the
## moving averages of cell mean and deviation have had time to become
## reasonable estimates of these values.  This parameter says how many
## scans that takes.

default.scans.to.learn = 15

## The moving average and moving average deviation for cells is
## updated so that new_value = k * old_value + (1-k) * new_data these
## are the default values of k for the mean and deviation moving
## averages, respectively.  The higher they are set, the slower the
## learning, but the less disruption from aberrant data.

stats.k = 0.95

## Stats are always updated while in the learning phase.  If the
## following flag is true, stats are also updated in the
## blip-finding phase

update.stats.while.blipping = TRUE

## When play is stopped (i.e. not just paused) by the user,
## should a new learning phase be required upon the next
## start of play?

restart.learning.after.stop = FALSE

## the size of the cells for which mean and absolute deviation
## are calculated (width, height) == (samples, pulses)

cell.dims = c(4, 4)

## These parameters set the high and low score thresholds.  If a
## sample has a score higher than the first value, or lower than the
## second value, it is considered "hot".  For the default radar
## scenario, we set the low threshold at its maximum negative value,
## which means we're effectively not using it, so that only higher
## than normal reflectivity is treated as "hot".  For grayscale video,
## we're interested in things either brighter or darker than the
## background, so we'd use something like -2.5 for the low threshold.

blip.score.threshold = c(2.5, -128)

## To be called a "blip", a contiguous patch of hot samples must
## have an apparent area between the following limits (inclusive)
## (in square metres)

blip.area.minmax = c(300, 20000)

## and a number of hot samples within the following inclusive limits

blip.samples.minmax = c(30, 5000)

## the angular range (number of pulses) must be within the following inclusive limits

blip.angular.minmax = c(2, -1)

## the radial range (number of sample slots) must be within the following inclusive limits

blip.radial.minmax = c(1, -1)


## an arbitrary expression for filtering patches, which can use these variables:
##
##   ns:    number of samples in the patch
##   area:  patch area in metres^2
##   perim: patch perimeter in metres
##   aspan: angular span of the patch (in pulses)
##   rspan: radial span of the patch (in samples)

blip.filter.expr = expression(perim^2 / (area * (4*pi)) < 5)

## should the patch filtering expression be used?

use.blip.filter.expr = FALSE

## to remove an important source of bias, the following should be set to TRUE
## so that samples determined to be parts of blips are not used in updating the
## stats cells containing them.  If this flag is FALSE, all samples in a cell
## are used, which for slow-moving targets, will tend to make the blip disappear
## as the cell mean and deviance are pushed up by the blip samples.
blip.exclude.blips.from.stats.update = TRUE

## Should diagonally-neighbouring (in pulse/echo space, not x/y space)
## hot samples be considered part of the same patch?  If not, we look
## only at a sample's 4 orthogonal neighbours in growing the
## (potential blip) patches.  Setting this to true will yield larger
## patches and blips (and possibly more of them through interaction
## with the cold score threshold).  It's not clear whether that is good
## or bad.

blip.use.diags = FALSE

## should blip centroids be calculated using area weighting?
## the alternative is intensity weighting

blip.area.weighting = FALSE

## In what folders should plugins be sought?
## This is a vector of path names, either absolute
## or beginning with "./" to indicate a path relative
## to the radR folder.

plugin.pathlist = "plugins"

## Should errors be logged to a file?

log.errors.to.file = TRUE

## To what file should errors be logged?

error.log.file = "radR.errors.txt"

## Should radR pause playing when an error is encountered?
## This should be set to false for unattended operation

pause.play.on.errors = TRUE

## width and height of default pixel matrix for scan conversion, in case the GUI
## is disabled.  If the GUI is enabled, the size of the plot window overrides
## this setting.

default.pix.mat.dim = c(800, 600)

## names of classes mapped to class numbers
class.named = list (
  cold = 1,
  hot = 2,
  blip = 3,
  other = 4,
  excluded = 5
  )

## internal values for class; these are used in RSS$class.mat
CLASS.VAL = list (
  cold = 0,
  hot = 1,
  blip = 2,
  other = 3,
  excluded = 4
  )

## which sample classes are shown in the scan-converted plot

show.class = list (
  cold = TRUE,
  hot = TRUE,
  blip = TRUE,
  other = FALSE,
  excluded = FALSE
  )

## a list of paths where palette files should be sought
## a palette file has a name of the form "XXX.palette.R"
## where XXX is the name of the palette

palette.pathlist = "palettes"

## which palette is used for each class in the scan-converted plot

class.palette = list (
  cold = "grayscale",
  hot = "dimprimary",
  blip = "brightprimary",
  other = "greenramp",
  excluded = "grayscale"
  )

## gamma values to use for each palette

class.gamma = list (
  cold = 1.0,
  hot = 1.0,
  blip = 1.0,
  other = 1.0,
  excluded = 1.0
  )

## tcl background colour for the rendering
pix.mat.background = "#000000"

## the plot data sources, with their display names
## the first item in a pair is the display name, the second
## is the name of the RSS item which holds the data

plot.data.sources = list (
  `raw sample values` = "scan.mat",
  `sample scores`   = "score.mat"
  )

## The plot data source.  One of the right hand sides from plot.data.sources

plot.data.source               = "scan.mat"

splash.text = "radR, Copyright (C) 2006-2015 John Brzustowski\nradR is free software and comes with\n    ABSOLUTELY NO WARRANTY.\nYou are welcome to redistribute radR\nunder certain conditions; for details,\nright click the mouse and do Help | License.\n\n"

## layer prototypes

## These determine radR's behaviour in opening / closing files.
## Plugins will typically add elements to this list for
## layers they know how to create, and these elements will
## inherit from the default element.
## In titles and messages, the following macros are substituted:
##
##   %NAME%  -> filename
##   %SIZE%  -> file size in bytes
##   %DATE%  -> file modification timestamp

layer.protos = list (
  default = strictenv (
    full.name         = "All files",
    open.read.title   = "Choose a file to open for input",
    open.write.title  = "Choose a file to open for output",
    not.found.title   = "File not found",
    not.found.msg     = "I want to read the file '%NAME%', but it doesn't exist.  What should I do?",
    file.exists.title = "Output file already exists",
    file.exists.msg   = "I want to create the file '%NAME%', but it already exists.  What should I do?",
    file.types        = ".*",
    header            = NULL,
    appendable        = FALSE,
    auto.versionize   = FALSE,
    auto.overwrite    = FALSE,
    auto.append       = FALSE,
    default.input.dir = ".",
    default.output.dir = "."
    )
  )

## Should file open dialogs always include the ".* = All files" filter?

all.files.in.dialogs = TRUE

## how long to pause on each iteration of the event loop when
## running under windows and not "playing", in milliseconds.
## This is meant to prevent a tight R-level loop using massive
## CPU time while doing nothing.

event.loop.sleeptime = 10

## how long to sleep between checking for completion of get.data threads, in milliseconds
## If a GUI is enabled, it will be updated before each such sleep period.

get.data.sleeptime = 100

## default names (in order) of items provided by get.scan.info

default.scan.info.names = c("pulses", "samples.per.pulse", "bits.per.sample", "timestamp",
  "duration", "sample.dist", "first.sample.dist",
  "bearing", "orientation", "latitude", "longitude")

## list of parameters to record when creating data files
## these are members of RSS

blip.finding.parms = c("default.scans.to.learn",
  "update.stats.while.blipping",
  "blip.exclude.blips.from.stats.update", "stats.k",
  "blip.score.threshold", "cell.dims", "blip.use.diags", "blip.area.weighting")

blip.filtering.parms = c("blip.samples.minmax",
  "blip.area.minmax", "blip.angular.minmax",
  "blip.radial.minmax")

#"use.blip.filter.expr", "blip.filter.expr"

other.parms = "user.comment"

