## svn $Id: radR.unix.conf.R 822 2011-08-26 13:42:36Z john $
##
##  RADR  CONFIGURATION  FILE
##
##  These are Unix-dependent parameters for the radR
##  base system.
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.
##
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.
##
##  Make sure to include a comma at the end of each item
##  in a list, except the last.
##
##  NOTE:  all elements of lists must be given names
##         e.g.   list(x=1, b=2) instead of list(1, 2)
##

## What plugins should radR load?
## This is a character vector, and an element "NAME"
## will cause the files "NAME.conf.R" and "NAME.plugin.R" to be loaded

plugins.to.load = c("zone", "blipmovie", "antenna", "tracker", "bliptrails", "help", "comments", "saveblips", "pointerinfo", "generic", "seascanarch", "rawarch", "underlay", "genblips", "gifmovie")

## A file to be source()'d after radR and plugins are loaded but before
## the event loop is installed.

startup.file = "main/startup.unix.R"

## what the null device is called in unix
null.device = "/dev/null"
