## svn $Id$
##                                                         
##  Unix-specific configuration for Simrad plugin.
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  

## Path to a multicast receiver program.  This program accepts the
## multicast address and port number as parameters, and dumps the
## data it receives to its standard output.  On linux,
## this program also accepts the bind address, which we force to "any".

multicast.receiver = "emcast"

## Function to accept a multicast address and port and make the
## appropriate command for obtaining a pipe

make.multicast.cmd = function(addr, port) sprintf("%s 0.0.0.0 %s %d", multicast.receiver, addr, port)

