## svn $Id: xir3000arch.conf.R 678 2010-11-04 16:08:32Z john $
##                                                        
##     XIR3000ARCH   PLUGIN   CONFIG
##                                                        
##  Read files recorded by Russell Technologies'          
##  radar digitizing software.      
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it is overwritten with new values when you exit       
##  radR.                                                 


## is this plugin enabled?
enabled = TRUE

## this plugin is not always on
always.on = FALSE

## names of the DSP versions, so that the user can tell us which one applies  
available.DSP.versions = c("DSP7", "DSP9")

## the version of the DSP used in recording the current file (for the old RIB board)
current.DSP.version = "DSP9"

## the magic number that RTI .rec files begin with  
file.magic = 0x1b5a04ce

## default parameters of RTI .REC files:
RTI.defaults = list (
  pulses.per.scan = 1024, 
  samples.per.pulse = 512,
  bits.per.sample = 8
  )

## for guessing timestamps from the base filename, we use a strptime-compatible
## format string:
date.guess.format = "%Y-%m-%d %H-%M-%S"

## in order to recognize the presence of a date in the base filename,
## we use a regular expression compatible with date.guess.format
date.guess.regexp = "((19)|20)[0-9][0-9]-[0-9]?[0-9]-[0-9]?[0-9] [0-9]?[0-9]-[0-9]?[0-9]-[0-9]?[0-9]"

## in case no timestamps are found in .REC files, we use the antenna rotation rate
## to set scan durations:
antenna.rpm = 25

## in case no heading data is found, this is what we use instead
default.heading = 0

## when choosing an archive, do we automatically use all .REC files in the selected folder,
## regardless of which file the user chooses to open?
use.all.folder.files = TRUE

