##  DECLUTTER  PLUGIN  CONFIG
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it may be overwritten with new values when you exit        
##  radR.                                                  

## should the plugin be enabled on load?

enabled = FALSE 

## the plugin is in either the learning or filtering mode

available.modes = c("learning", "filtering")

## the currently selected mode

current.mode = "learning"

## minimum mean sample occupancy at which blip is treated as clutter.
## For example, blip.cutoff = 0.01 means any blip having a mean sample
## occupancy (across all its samples) greater than 1% is filtered out.

cutoff = 0.0030

## the default file from which to load a clutter map
clutter.filename = NULL

## should we display occupancy rates as OTHER in the plot window?
plot.occrate = FALSE

## default palette for displaying occupancy rates
default.palette = "greenramp"

## default gamma for displaying occupancy rates
default.gamma = 2.0
