## svn $Id: default.antenna.R 574 2010-05-11 02:07:15Z john $
##
##  RADAR  ANTENNA SPECIFICATION  FILE
##                                                         
##  These are parameters describing a specific radar       
##  set-up.                                                
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it may be overwritten with new values by radR.         
##                                                         
##  Each item definition except the last must end with     
##  a comma (",").                                         
##                                                               
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list, except the last.                            
##                                                         
##  NOTE:  all elements of lists must be given names       
##         e.g.   list(x=1, b=2) instead of list(1, 2)     


## Description (for humans) of what antenna setup this file is
## for.  This must be a string surrounded by single or double
## quotes.

antenna.desc = "Default antenna.  You can use the antenna plugin to customize this."

## Antenna type.
## This must be one of:
##   "dish" - a parabolic dish
##   "tbar" - an open-array T-bar antenna

antenna.type = "dish"

## Angle of the antenna beam axis above the horizontal, in degrees.
## For typical configurations, this should be zero.

antenna.angle = 0

## Horizontal aperture of the antenna, in degrees.  This is the
## angular width of the instantaneous region "seen" by the
## antenna.

antenna.aperture.h = 3

## Vertical aperture of the antenna, in degrees.  This is the
## angular height of the instantaneous region "seen" by the
## antenna.  (should equal aperture.h if type == "dish")

antenna.aperture.v = 3

## Geographic location of the radar.  This will be overridden by
## any GPS information provided by the radar data, and is
## optional.

## latitude, in degrees North (negative for South of the equator)

latitude = 0

## longitude, in degrees West (negative for east of Greenwich)

longitude = 0

## elevation, in metres above sea level

elevation = 0

## bearing offset: an angle in degrees clockwise from N.
## This is used for two purposes:
## 1. For a stationary antenna, (i.e. one for which scan.info$bearing is always 0),
##    this is the azimuth angle corresponding to the first pulse in each sweep.
##
## 2. For a moving antenna, this is the offset between the ship's axis
##    (whose azimuth is reported in scan.info$heading) and the antenna's axis.
##
## In both cases, scan.info$heading + scan.info$bearing.offset will be
## the compass angle corresponding to the first pulse in a sweep.

bearing.offset = 0

## What is the rotation axis?  Specify as (azimuth, elevation) in
## degrees clockwise from North, and degrees above horizontal.  In
## most configurations this will be the z axis, given by (0, 90).  If
## the scanner can be tilted, the first number is the compass
## direction toward which the rotation axis is tilted, and the second
## number is the new axis elevation angle (i.e. 90 - the amount of
## tilt).

rotation.axis = c(0, 90)

## In case the trigger delay was not properly set on the digitizing
## card, the following parameter can be used to eliminate a hole in
## the middle of the data.  It is in metres, and indicates the true
## range of the first sample.  Positive means the first true echo
## sample is not at the beginning of the scanline, and serves to close
## a hole.  Negative means some number of true echo samples are
## missing, and serves to open a hole corresponding to the missing
## data.

first.sample.dist = 0

## Parameters to be used for specific plugins
## each item name is a plugin, and the list corresponding to it is
## a set of parameter values to be used for this antenna by that plugin.
## These values may be modified by the plugin's code.

antenna.plugins = list (

  ## parameters for seascan's A/D converter
  seascan = list (
    gain   = 255,
    offset = 61
    ),

   ## parameters for the XIR3000C A/D converter
  xenex = list (
    antenna        = "Furuno FR1954C-BB-Remote",
    neg.video      = TRUE,
    trig.offset    = 1600,
    vid.div        = 0,
    vid.xgain      = 255
    )
  )

