## svn $Id: seascanarch.conf.R 574 2010-05-11 02:07:15Z john $
##                                                            
##  SEASCANARCH  INTERFACE  CONFIG
##                                                            
##  These are parameters for the seascanarch plugin.          
##  This plugin is an interface for reading/writing           
##  seascan archive files.                                    
##                                                            
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because         
##  it is overwritten with new values when you exit           
##  radR.                                                     
##                                                            
##  Lines beginning with "#" and blank lines are preserved    
##  but comments at the ends of lines are not.                
##                                                            
##  Make sure to include a comma at the end of each item      
##  in a list.  A list definition should look like this:      
##                                                            
##     what.ever = list (                                     
##        something = 45,                                     
##        something.else = 55                                 
##     )                                                      
##                                                            
##  The first and last lines must not have any actual list    
##  items on them, and all items must be named                
##  (i.e. NAME = THING, instead of just THING)                


enabled = TRUE 

## For ungated data, we set a target number of azimuths
## here. For each target azimuth, the closest (in bearing)
## real pulse is used.  This may lead to replication or deletion
## of real pulses in generating the gated raw scan data.

desired.azimuths = 1024 

## For ungated data, there may be no real pulse very close to the
## desired azimuth if some data are lost.  This parameter will
## limit how far away a real pulse can be from the desired azimuth.
## If enough data has been lost that the limit is exceeded,
## a warning is printed. A value of K here means within K
## desired azimuths (i.e. K * 2 * pi / desired.azimuths radians)

max.azimuth.err = 1.0 

## Set the following flag to true if your ungated data appears
## to have black radial streaks when viewed in the plot window.
##
## When recording ungated data on a slower computer, Seascan
## appears to sample some pulses at too late a time, missing the
## bulk of the echo.  This appears to happen on the last pulse
## for a given azimuth/bearing, according to the internal
## RSI_LUT field in the angle block of the raw archive.
## This flag causes such "pulses" to be ignored

skip.changeover.pulse = TRUE


