## svn $Id: gui.windows.conf.R 263 2009-03-04 16:56:59Z john $
##                                                         
##  RADR GUI CONFIGURATION FILE (WINDOWS)
##                                                         
##  These are Windows-dependent parameters for the radR    
##  GUI.                                                   
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it may be overwritten with new values by radR.
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list, except the last.                            
##                                                         
##  NOTE:  all elements of lists must be given names       
##         e.g.   list(x=1, b=2) instead of list(1, 2)     
##                                                         

### The default folder for initially looking for data files.

default.dir = "."

## The icon (a square .bmp file renamed to .ico) that
## appears in the window titlebar and the window-tabber (Alt-TAB)
## Eventually, we'll use the "wm iconphoto" instead of "wm iconbitmap" tcl command
##      

application.icon = "gui/radR.ico"

default.font = "Sans 8"

console.font = "{Courier New} 8"

plot.info.font = "{Courier New} 8"

compass.label.font = "{Courier New} 8"

## Does this platform generate Tk <MouseWheel> events?
## if not, we assume Button-4/5 are generated instead
## for mousewheel roll forwards/backwards

have.mousewheel.events = TRUE

## Does this platform need to have its <MouseWheel> (or Button-4/5)
## events redirected in order to reach unfocused child windows?
## Setting this flag to TRUE means that MouseWheel or Button-4/5
## events received by a toplevel window will be redirected to
## the child window at the current mouse location.

redirect.mousewheel.events.to.children = TRUE

## The bit index for each key state for Motion events:
## This is the index when the integer state value is converted
## to bits using intToBits.

motion.state.key.bits = list (
  Shift = 1,
  Control = 3,
  Alt = 18
  )

## how much to offset a newly torn-off menu window so that the pointer
## is comfortably inside its titlebar

tearoff.menu.window.offset = c(-30, -10)
