## svn $Id: gui.bindings.conf.R 213 2009-02-12 16:15:11Z john $
##                                                        
##   GUI EVENT BINDING FILE           
##                                                        
##  This file provides bindings between user-generated    
##  events such as keypresses and mouse clicks and the    
##  virtual GUI events that actually do the work.         
##  Do not edit this file while radR is running, since    
##  it may be overwritten by radR.                        
##                                                        
##  You can customize this file, but keep a backup copy   
##  because if you mess it up, you'll disable radR.       
##                                                        
##  This file has the following form:
##  VIRTUAL_EVENT_NAME = list (
##    WINDOW_TAG1 = c(SEQ_1_1, SEQ_1_2, ...)
##    WINDOW_TAG2 = c(SEQ_2_1, SEQ_2_2, ...)
##    , ...
##    ),
##   ...
##  The list gives the mouse/key event sequences that
##  generate each virtual event.
##  WINDOW_TAG is either the name of a window such as:
##
##    .plot:  the plot window                             
##    .pctl:  the plot control/options window             
##    .play:  the player window                           
##    .blip:  the blipping parameters window              
##    .cons:  the R console window                        
##    .cmd:   the top-level popup-menu window             
##    .epal:  the palette editor window
##
##     Or a window type such as
##      
##      Spinbox:  all numeric entry boxes with up/down controls
##      Text:     all text entry widgets
##      Scale:    all numeric slider bars
##      Toplevel: all top level windows
##      all:      every window and widget
##
##    Each SEQ_i_j is one of the following:
##      
##     - a keyname: e.g. "-", "<Alt-Up>" 
##     - a mouse event: e.g. "<Button-2>"
##     - the string "command ???" where "???" is some tcl code
##       In this case, the widget's "command" will be configured
##       to generate the given virtual event.  This can be used
##       for buttons or Scales, e.g.
##     - a regular or virtual event name possibly followed by one or more Tk event parameter
##       substitution strings such as "%x"; note that virtual events are limited in the parameter
##       substitutions they allow, so the virtual <<MODIFIER-MouseWheel>> events use "%x"
##       rather than "%D" as the mousewheel step size.
##       e.g.  ROTATE_PLOT_SMALL_STEP = list (.plot.frame = "<<Shift-MouseWheel>> %x")
##       passes the x field from the virtual event <<Shift-Mousewheel>> to the
##       virtual event <<ROTATE_PLOT_SMALL_STEP>>.  The mousewheel
##       redirector generates virtual mousewheel events with a mousewheel
##       delta passed in the %x field.
##
##    Warning: no VIRTUAL_EVENT_NAME should appear more than once in
##    this file, and no WINDOW_TAG should appear more than once within
##    a given VIRTUAL_EVENT_NAME list.  Multiple sequences for a single
##    virtual event and window should be combined into a vector, such as:
##
##      GENERATE_MOUSEWHEEL_UP = list (all = c("<Alt-Up>", "<Button-4>"))
##
##    which says that for every window, both the Alt-Up key and MouseButton 4
##    generate a mousewheel up virtual event. (Button 4/5 are typically
##    used to pass mousewheel single-step events on unix).
##    
##  radR handles a virtual event by calling the function     
##  GUI$evt[VIRTUAL_EVENT_NAME] in gui.R                   
##  Some virtual events are generated internally by         
##  radR, and although they are not bound to any user-     
##  generated events by default, they are listed here to   
##  allow you to do so.                                    

## remap the keypad Enter key to behave like the Return key
## in text, entry, and spinbox widgets

ENTER_KEY_PRESS = list (
  Entry = "<KP_Enter>",
  Text = "<KP_Enter>",
  Spinbox = "<KP_Enter>"
  )

ENTER_KEY_RELEASE = list (
  Entry = "<KeyRelease-KP_Enter>",
  Text = "<KeyRelease-KP_Enter>",
  Spinbox = "<KeyRelease-KP_Enter>"
  )

## pop up the radR menu using the right mouse button
## in any window (but don't use "all" as the window,
## since we occasionally use the right button for other
## things, and all can't be overridden by an individual
## window binding).

POPUP_RADR_MENU = list (
## these work for Tk plotting mode
  .plot.frame.canvas = list (
    "plot||compass||ring" = "<Button-3>"
    ),
## this works for fast plotting mode  
  .plot.frame = "<Button-3>",

## other windows:  
  .blip = "<Button-3>",
  .pctl = "<Button-3>",
  .cons = "<Button-3>",
  .play = "<Button-3>"
  ) 

## zoom in the plot window by the default increment
ZOOM_IN_PLOT_STEP = list (
  .plot = "+"
  ) 

## zoom out the plot window by the default increment
ZOOM_OUT_PLOT_STEP = list (
  .plot = "-"
  ) 

## zoom in/out by a specified number of default steps
## To change the zoom orientation (i.e. does moving the
## mousewheel up zoom in or zoom out?), replace the value
## of pps.zoom.factor in gui.conf.R with 1 divided by the existing
## value.  e.g. if the value of pps.zoom.factor is 1.25,
## change it to 0.8.

ZOOM_BY_STEPS = list (
  .plot.frame = "<<MouseWheel>> %x",
  .plot.frame.canvas = "<<MouseWheel>> %x"
  ) 

## set the plot geometry to default pan, zoom, rotation, and compass radius
PLOT_TO_DEFAULT_VIEW = list (
  .plot = "=",
  .plot.frame = "<Shift-B2-ButtonRelease>",
  .plot.frame.canvas = "<Shift-B2-ButtonRelease>"
  ) 

## rotate the plot by a large step
ROTATE_PLOT_BIG_STEP = list (
  .plot.frame = "<<Control-MouseWheel>> %x",
  .plot.frame.canvas = "<<Control-MouseWheel>> %x"
  ) 

## rotate the plot by a small step
ROTATE_PLOT_SMALL_STEP = list (
  .plot.frame = "<<Control-Shift-MouseWheel>> %x",
  .plot.frame.canvas = "<<Control-Shift-MouseWheel>> %x"
  ) 

## Some systems use Button-4 and Button-5 to provide mousewheel
## events, so have these generate mousewheel events everywhere.
## Also, provide Alt-key equivalents for mousewheel function

GENERATE_MOUSEWHEEL_UP = list (
  all = c("<Alt-Up>", "<Button-4>")
  ) 

GENERATE_MOUSEWHEEL_DOWN = list (
  all = c("<Alt-Down>", "<Button-5>")
  ) 

GENERATE_CONTROL_MOUSEWHEEL_UP = list (
  all = c("<Alt-Control-Up>", "<Control-Button-4>")
  ) 

GENERATE_CONTROL_MOUSEWHEEL_DOWN = list (
  all = c("<Alt-Control-Down>", "<Control-Button-5>")
  ) 

GENERATE_SHIFT_MOUSEWHEEL_UP = list (
  all = c("<Alt-Shift-Up>", "<Shift-Button-4>")
  ) 

GENERATE_SHIFT_MOUSEWHEEL_DOWN = list (
  all = c("<Alt-Shift-Down>", "<Shift-Button-5>")
  ) 

GENERATE_CONTROL_SHIFT_MOUSEWHEEL_UP = list (
  all = c("<Alt-Control-Shift-Up>", "<Control-Shift-Button-4>")
  ) 

GENERATE_CONTROL_SHIFT_MOUSEWHEEL_DOWN = list (
  all = c("<Alt-Control-Shift-Down>", "<Control-Shift-Button-5>")
  ) 

## left-button dragging in the plot window either moves the plot, adjusts 
## the rangerings, or adjusts the compass ring, depending
## on whether no key, the shift key, or the control key is
## pressed at the time

START_PLOT_DRAG = list (
  .plot.frame = "<Button-1>",

  ## Because in Tk plotting mode there will often be objects on the canvas
  ## that have their own drag semantics, we bind the plot drag specifically
  ## to those items that don't have such semantics; i.e. the background plot image,
  ## the compass, and the range rings.

  .plot.frame.canvas = list (
    "plot||compass||ring" = "<Button-1>"
    )
  ) 

END_PLOT_DRAG = list (
  .plot.frame = "<B1-ButtonRelease>",
  .plot.frame.canvas = list (
    "plot||compass||ring" = "<B1-ButtonRelease>"
    )
  ) 

START_INFO_WIN_DRAG = list (
  .plot.frame.info = "<Button-1>"
  ) 

CONTINUE_INFO_WIN_DRAG = list (
  .plot.frame.info = "<Button1-Motion>"
  ) 

END_INFO_WIN_DRAG = list (
  .plot.frame.info = "<B1-ButtonRelease>"
  ) 

DRAG_RANGE_RINGS = list (
  .plot = c("<Shift-Button1-Motion>", "<Shift-B1-ButtonRelease>"),
  .plot.frame.canvas = c("<Shift-Button1-Motion>", "<Shift-B1-ButtonRelease>")
  ) 

DRAG_COMPASS_RING = list (
  .plot = c("<Control-Button1-Motion>", "<Control-B1-ButtonRelease>"),
  .plot.frame.canvas = c("<Control-Button1-Motion>", "<Control-B1-ButtonRelease>")
  ) 

## left-double-clicking in the plot window sets the plot
## origin to the point under the mouse

SET_PLOT_ORIGIN = list (
  .plot = "<Double-Button-1>"
  ) 

## the pointer information window, giving details about the
## location plotted under the mouse, pops up whenever the mouse
## moves

SHOW_POINTER_INFO = list (
  .plot.frame = "<Motion>",
  .plot.frame.canvas = "<Motion>",
  .plot.frame.info = "<Motion>"
  ) 

ENABLE_POINTER_INFO = list (
  .plot.frame = "<Enter>",
  .plot.frame.canvas = "<Enter>"
  ) 

DISABLE_POINTER_INFO = list (
  .plot.frame = "<Leave>",
  .plot.frame.canvas = "<Leave>"
  ) 

## play-controller events

START_PLAY = list (
  .play.play = "<B1-ButtonRelease>"
  ) 

PAUSE_PLAY = list (
  .play.pause = "<B1-ButtonRelease>"
  ) 

STOP_PLAY = list (
  .play.stop = "<B1-ButtonRelease>"
  ) 

PLAY_ONE_SCAN = list (
  .play.play1 = c("command", "<<MouseWheel>>")
  ) 

TO_START= list (
  .play.tostart = "command"
  )

TO_END = list (
  .play.toend = "command"
  )

TOGGLE_RECORDING = list (
  .play.record = "<B1-ButtonRelease>"
  ) 

PLAY_SLIDER_MOVED = list (
  ## the "-x" is to preface the new slider value which gets appended by Tk,
  ## generating a virtual event which provides the new slider value as "x"
  .play.slider = "command -x"
  ) 

SEEK_SCAN_FWD_REV = list (
  ## seek forward or backward to a new scan according to argument
  .plot.frame = "<<Shift-MouseWheel>> %x",
  .plot.frame.canvas = "<<Shift-MouseWheel>> %x"
  ) 

IGNORE = list (
  ## delete the bindings for mousewheel up and down on unix for
  ## text elements, since we will explicitly bind these for all platforms
  Text = c("<Button-4>", "<Button-5>")
  ) 

SCROLL_TEXT_WINDOW = list (
  Text = "<<MouseWheel>>"
  ) 


##  Events generated internally by radR.  These are not bound to keyboard or       
##  mouse events by default, but you can do so.  They allow radR to change the     
##  appearance of the GUI in response to internal events, such as the loading of a 
##  plugin, end of file on archive playback, etc.  Some of these request an        
##  action from the GUI, such as popping up a confirmation dialog.                 

## FIXME: document the parameters for these events.

CONFIRM_QUIT             = list() 
CREATE_WINDOWS           = list() 
ENABLE_CONTROLS          = list() 
HAVE_PLUGINS             = list() 
PLUGIN_LOADED            = list() 
PLUGIN_UNLOADED          = list() 
POPUP_DIALOG             = list() 
RECREATE_TEAROFFS        = list() 
RESET_PROGRESS           = list() 
SAVE_CONFIG              = list() 
SET_PLOT_CURSOR          = list() 
SET_PORT                 = list() 
SHOW_BUSY                = list() 
SHOW_ERROR               = list() 
UPDATE_PLOT_PARMS        = list() 
UPDATE_PLOT_WINDOW       = list() 
UPDATE_PLOT_WINDOW_TITLE = list()
