#include <stdlib.h>
#include <malloc.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <signal.h>
#include <sys/ipc.h>
#include <sys/shm.h>
#include "radR.h"
#include "patchify.h"
#include "radRprot.h"
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <X11/extensions/XShm.h>
#include <tcl.h>
#include <tk.h>
#include <tkInt.h>
#include "radRvars.h"
