## $Id: example.conf.R 134 2009-01-20 15:04:53Z john $
##                                                        
##              EXAMPLE PLUGIN CONFIG                     
##                                                        
##  These are parameters for the sample plugin "example"  
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it may be overwritten with new values if you choose   
##  to save the configuration when you exit radR.         
##                                                        
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.            
##                                                        
##  Make sure to include a comma at the end of each item  
##  in a list.  A list definition should look like this:  
##                                                        
##     what.ever = list (                                 
##        something = 45,                                 
##        something.else = 55                             
##     )                                                  
##                                                        
##  The first and last lines must not have any actual list
##  items on them, and all items must be named            
##  (i.e. NAME = THING, instead of just THING)            


## is the plugin enabled upon loading?  If TRUE, then
## the plugin's hook functions are installed and enabled.

enabled = TRUE

## this is an example of a plugin configuration option

a.string = "Put something here"

## you can also use lists, but make sure to give the list
## items names.  The closing parenthesis for a list
## MUST appear on its own line, with AT LEAST one space or TAB
## preceding it.

my.favourite.things = list (
  do = "a deer, a female deer",
  re = "a drop of golden sun"
  )

## vectors are fine too
## The closing parenthesis for a vector MUST NOT appear on its
## own line preceded by whitespace.  It may appear on its
## own line if it is the first character in that line.

my.data = c(3.141, 2.71828, 1.414)
