## svn $Id: audio.conf.R 574 2010-05-11 02:07:15Z john $
##
##      AUDIO  PLUGIN  CONFIG
##
##  These are parameters for the radR plugin "audio"
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.
##
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.
##
##  Make sure to include a comma at the end of each item
##  in a list.  A list definition should look like this:
##
##     what.ever = list (
##        something = 45,
##        something.else = 55
##     )
##
##  The first and last lines must not have any actual list
##  items on them, and all items must be named
##  (i.e. NAME = THING, instead of just THING)
##


## is the plugin enabled upon loading?

enabled = FALSE

## options for samples per second per channel

samples.per.second.opts = c(11025, 22050, 44100)

## samples per second per channel
samples.per.second = 22050

## options for bits per sample

bps.opts = c(8, 16)

## current choice of bps

bps = 16

## options for number of channels (1 or 2)

num.channels.opts = c(1, 2)

## current choice of num channels

num.channels = 2

## maximum amount of audio saved in one file (in milliseconds)
## this should be large enough to accomodate a full radar scan,
## so at least 2400.

max.audio.per.file = 3000

## size of MCI's internal buffer for recording.  This is a technical internal
## parameter and should probably be left at 4 (seconds).

rec.buff.size = 4

## the folder in which to save recorded audio files

wav.folder = "plugins/audio"

## the format of .wav file names, with the usual strftime '%' replacements
## available for the current scan's timestamp

filename.format = "aud%Y%m%d%H%M%S.wav"

## R boolean expression that determines whether the most recent audio
## will be saved.  Evaluated at the end of each scan.

save.filter = expression(RSS$num.blips > 3 && RSS$num.blips < 400)
