## svn $Id: oldblipmovie.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##  BLIPMOVIE  PLUGIN  CONFIG
##                                                         
##  These are parameters for the radR plugin saveblips     
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## Is this plugin enabled upon loading?

enabled = FALSE

## blip movies are saved in three files named
## XXX.bma
## XXX.blp
## XXX.smp
## This option is for setting the "XXX" portion,
## and can include a pathname.

movie.basename = "bmovie"

