## svn $Id: gifmovie.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##  GIFMOVIE  PLUGIN  CONFIG
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## is the plugin enabled upon loading?  If TRUE, then
## the plugin's hook functions are installed and enabled.

enabled = FALSE

## what programs are used to capture window contents into a file.
## By default, the programs distributed with radR are used.
## No file extension is required.  The programs and any options
## must be in the same order as frame.file.formats (see below).

capture.progs = c("plugins/gifmovie/gifsicle", "plugins/gifmovie/win2rgb")

## should we check whether the capture programs are correct and available?

check.capture.progs = TRUE

## delay (in 1/100 of a second) between frames in the
## animated GIF

frame.delay = 20 

## delay (in # of scans) before GIFmovie begins
## recording the plot window after user hits "Play"

skip.first.scans = 0 

## maximum # of scans to record at a time
## 0 = no maximum

max.scans = 0 

## directory in which to record individual frames

frame.dir = "GIFmovie" 

## formatting strings for frame file names, one per frame file format.
## This should include a "%0Nd" code where N is the
## number of digits to use in frame filenames, and end in ".gif" or ".rgb" respectively.
## e.g. "frame%03d.gif" will record frames in files named
##      frame001.gif, frame002.gif, frame003.gif, ... frame999.gif
## in the directory given by frame.dir

frame.filename.template = c("frame%06d.gif", "frame%06d.rgb")

## the path of the final movie file, which combines all the frames
## into an animated GIF

movie.filename = "GIFmovie/movie.gif" 

## should frames be deleted after merging?

delete.frames.after.merging = TRUE

## should the movie loop flag be set?

loop.movie = TRUE

## different window capture styles:

window.styles = c("just the plot window contents", "the plot window including frame and titlebar", "the whole desktop")

## which of the above styles is in effect?

window.style = 2

## different capture modes

capture.modes = c("once for each scan, after processing", "continuously at a fixed time interval, regardless of activity")

## which of the above modes is in effect

capture.mode = 1

## interval between consecutive captures, in /100ths of a second, for when timewise is TRUE

capture.interval = 20

## frame file formats:

frame.file.formats = c(".gif - slow and low color resolution", ".rgb - fast and higher color resolution, but individual frames not accessible")

## which of the above formats is being used

frame.file.format = 2
