##  Configuration for radarcam plugin.
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.

## is this plugin currently enabled when loaded?
enabled = TRUE

## The following flag says that this plugin is enabled whenever
## it is loaded.  TRUE here makes the "enabled" parameter redundant.
always.enabled = TRUE

## name of pipe from which sweeps are read
## sweeps are in the same format as used by inradarch, except uncompressed
pipename = "/tmp/radarcam"
