##  Configuration for radarcam plugin.
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.

## is this plugin currently enabled when loaded?
enabled = TRUE

## The following flag says that this plugin is enabled whenever
## it is loaded.  TRUE here makes the "enabled" parameter redundant.
always.enabled = TRUE

## url from which to read sweeps
default.sweepURL = "http://localhost:8080"

## timeout (in seconds) after which the source is deemed "finished"
default.timeout = 20
