## This Makefile is called recursively from the Makefile in the parent directory,
## and requires the variables defined there.

$(eval $(AT_MAKEFILE_START))

PLUGIN_EXTRA_R_FILES = pointerinfo.windows.conf.R pointerinfo.unix.conf.R

$(eval $(AT_MAKEFILE_END))
