## svn $Id: pointerinfo.conf.R 825 2011-08-26 13:54:50Z john $
##                                                         
##  POINTERINFO  PLUGIN  CONFIG
##                                                         
##  These are parameters for the pointerinfo plugin        
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## should the plugin be enabled on load?

enabled = TRUE 

## a list of items optionally displayed by the floating
## box in the plot window

show = list ( 
  ## range and bearing from plot centre
  range.bearing = TRUE,

  ## spatial coordinates
  spatial.coords = TRUE,
  
  ## raw sample value and sample z-score
  sample.details = TRUE,
  
  ## mean and absolute deviation of cell containing sample
  cell.stats = TRUE,

  ## number of samples, area, radial and angular range of patch
  patch.stats = TRUE 
  ) 

## Should info window contents be copied automatically to the clipboard?

auto.clipboard = FALSE

## Functions to format data for what's under the plot cursor.
## The first is for formatting what is actually shown in the floating info window.
## The second is for formatting what is copied to the clipboard.

formatter = list ( 
  range.bearing = function (rb) {
    sprintf("range: true=%7.3f km, ground=%7.3f km\nbearing=%5.1f°  elev. angle=%4.1f°", rb[2]/1000, rb[1]/1000, rb[3], RSS$scan.info$antenna.angle[1])
  },

  spatial = function (xyz, t) {
    sprintf("xyzt=(%6.0f, %6.0f, %5.0f, %s) m,s", xyz[1], xyz[2], xyz[3], format(structure(t, class="POSIXct"), "%H:%M:%OS3", tz=RSS$timezone ))
  },
  
  sample.details = function (sc, sd) {
    sprintf("Sample %4d  Pulse %4d\nValue = %5d Score = %7.3f", sc[1],
            sc[2], sd[1], sd[2])
  },

  cell.stats = function (cc, cs) {
    sprintf("Cell [%d, %d]\nMean = %5d  Abs. Dev. = %5d", cc[2], 
            cc[1], cs[1], cs[2])
  },
  
  patch.stats = function (ind, ps) {
    ## ind[1] - index of this patch among all patches
    ## ind[2] - index of this blip among all blips (or 0, if not a blip)
    ## ps[]: a row from RSS$patches, with column names
    sprintf("%s: xyzt=(%6.0f, %6.0f, %6.0f, %s)\nSamples: %5d  Area: %6.0f m^2  Perim: %6.0f m\nIntensity: %.3f   Max: %5.3f\nSpan: radial=%4d angular=%4d",
            if (ind[2] > 0) "Blip #" %:% ind[2] else "Patch #" %:% ind[1],
            ps$x, ps$y, ps$z, format(ps$t, "%H:%M:%OS3"), ps$ns, ps$area, ps$perim, ps$int, ps$max, ps$rspan, ps$aspan)
  } 
  ) 

clipboard.formatter = list ( 
  range.bearing = function (rb) {
    sprintf("%.3f\t%.3f\t%.3f\t%.2f", rb[2]/1000, rb[1]/1000, rb[3], RSS$scan.info$antenna.angle[1])
  },
  
  spatial = function (xyz, t) {
    sprintf("%6.0f\t%6.0f\t%6.0f\t.3f", xyz[1], xyz[2], xyz[3], t)
  },
  
  sample.details = function (sc, sd) {
    sprintf("%d\t%d\t%d\t%.2f", sc[1], sc[2], sd[1], sd[2])
  },
  
  cell.stats = function (cc, cs) {
    sprintf("%d\t%d\t%d\t%d", cc[2], cc[1], cs[1], cs[2])
  },
  
  patch.stats = function (ind, ps) {
    sprintf("%d\t%d\t%6.0f\t%6.0f\t%6.0f\t%s\t%d\t%.0f\t%.3f\t%.3f\t%d\t%d\t%.0f", ind[1], ind[2], ps$x, ps$y, ps$z, format(ps$t), ps$ns, ps$area, ps$int, ps$max, ps$aspan, ps$rspan, ps$perim)
  }
  )
