## svn $Id: seascan.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##     SEASCAN  INTERFACE  CONFIG
##                                                         
##  These are parameters for the seascan plugin.           
##  This plugin is an interface to the SeaScan client      
##  library.                                               
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


enabled = FALSE 

## The following flag says that this plugin is enabled whenever
## it is loaded.

always.enabled = TRUE

## Full path to the Rutter install directory.
## This should be the location where the server program is found

server.path = "c:/Program Files/Rutter/Sigma S6/SeaScanRT/SeaScan.exe" 

## The directory where the Client12.dll library is stored

client.lib.dir = "c:/Program Files/Rutter/Sigma S6/SeaScanRT" 

## The name of the client library is compiled into radR's seascan.dll
## and cannot be changed without recompiling.

client.lib.name = "Client12.dll"

## Should radR try to start the seascan server when this plugin
## is loaded, and stop it when unloaded?

start.and.stop.server = TRUE 

## The name of the binary SeaScan configuration file actually
## used by seascan.

binary.config.file = "plugins/seascan/SeaScan0.bin" 

## On some networks, the seascan client.dll returns many hosts as being possible
## Seascan servers, and trying to obtain a status from each of
## these causes a long wait (for timeouts on each request) at
## startup of the module.  To have the seascan module ignore
## unknown hosts, set the following flag to TRUE:

ignore.unknown.hosts = TRUE

## if ignore.unknown.hosts is TRUE, only the following hosts are
## viewed as possible Seascan servers

known.hosts = "local" 

## the default radar description file

radar.desc.file = "plugins/seascan/furuno1954C-BB.radar.R" 

## The value for the ACPs field in SeaScan0.bin files.
## This does not appear to directly affect anything, but it's the
## value you enter as "Azimuth Resolution" in SeaScanRCU.exe
## SeaScanRCU treats that entered value as determining the # of pulses
## sampled per scan regardless of PRF mode.  This plugin allows
## for a different # of pulses per scan for each PRF mode, by specifying
## different QuadrantSize values for each PRF mode, but SeaScanRCU will
## overwrite these with its own constant value if run on this plugin's
## SeaScan0.bin file.
##
## Here we specify the maximum allowable for SeaScan.

binfile.ACPs.field = 4096 

## The "current" modeline (representing range resolution and coverage)

current.modeline = 8

