## svn $Id: xenex.conf.R 622 2010-07-12 20:21:50Z john $
##                                                         
##     XENEX    PLUGIN   CONFIG
##                                                         
##                                                         
##  Read data from Russell Technologies' IntegRadar server 
##  or XIR3000 USB radar digitizing hardware.              
##                                                         
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  


## is this plugin enabled?

enabled = TRUE 

## The following flag says that this plugin is enabled whenever
## it is loaded.

always.enabled = TRUE

## path to the Xenex client library

client.lib = "c:/RTI SDK 1.5.0.008/Release/CANRib.dll"

## allowed values for config items with restrictions
## Those items which are a vector give all allowed items.
## Those items which are an expression return TRUE or FALSE,
## according to whether the value of "x" is allowed.

allowed = list ( 
  ## allowed bits per sample is only 8 (this is actual data bits)
  bps = 8,
  
  ## allowed dsp versions
  dsp = c(7, 9),

  ## allowed values for master
  master = c(TRUE, FALSE),

  ## allowed values for active
  active = c(TRUE, FALSE),

  ## allowed antenna names (filled in at load time)

  antenna = c("Anritsu", "Default Slave Alone", "Furuno",
    "Furuno FR-2125 8.0ft", "Furuno FR-8111 6.5ft", "Furuno FR1832",
    "Furuno FR1932", "Furuno FR1942", "Furuno FR1954C-BB",
    "Furuno FR1954C-BB-Remote", "Furuno FR7111", "JRC 2000",
    "JRC 2253", "JRC 2254", "Koden", "Raymarine", "Raytheon",
    "Raytheon R10XX", "Raytheon R41X", "SIMULATOR Furuno EG3000",
    "SIMULATOR JRC 2253", "SIMULATOR JRC 2254", "SIMULATOR Raytheon"),

  ## allowed range.index values:
  range.index = 0:8,

  ## allowed neg.video values:
  neg.video = c(TRUE, FALSE),

  ## allowed vid.xgain values:
  vid.xgain = expression( x >= 0 && x <= 15),
  
  ## allowed trig.offset values:
  trig.offset = expression( x >= 0 && x <= 65535),

  ## allowed cable.length values:
  cable.length = expression( x >= 0 && x <= 255),
  
  ## allowed vid.div values:
  vid.div = expression( x >= 0 && x <= 255)
  ) 

## which config items require a restart of the device?

requires.restart = list (
  active       = TRUE,
  antenna      = TRUE,
  bps          = FALSE,
  cable.length = FALSE,
  dsp          = TRUE,
  master       = TRUE,
  mode         = TRUE,
  neg.video    = FALSE,
  range.index  = FALSE,
  trig.offset  = FALSE,
  vid.div      = FALSE,
  vid.xgain    = FALSE
  )

## a list of static host names we will assume have servers
static.hosts = c("LOCALHOST", "XIR3000C")

## should we probe the net for IntegRadar hosts?
probe.net.hosts = FALSE

## how long to wait for IntegRadar hosts to respond to a "who's a server" message,
## in seconds

get.hosts.timeout = 2 

## how long to keep the messagebox "Opening device" showing when a port is
## started up, in seconds

start.up.message.time = 6 

## What clock divisors are used to present the user with a set of range-cell sizes
## for the USB board?
## 
## Note:  range.cell.sizes = 3e8 / (sample.rate * 1e6 / (usb.vid.divs)) / 2
##          (in metres)              (in MHz)

usb.vid.divs = 0:32

## Default configurations by port type.  This list also provides the
## names of configuration items allowed for each port type.

defaults = list ( 
  USB = list ( 
    antenna = "Decca BridgeMaster E",
    ## bits per sample; this is fixed as 8 
    bps = 8,
    dsp = 7,
    neg.video = TRUE,
    ## sample.rate: (MHz) can be 27, 54, or 100
    sample.rate = 100,
    ## vid.div: this is the digitizer clock divisor (minus 1); i.e. if set to n, then
    ## each sample comes from integrating over n+1 clock ticks.
    ## This value provides the default 
    vid.div = 0,
    ## trig.offset: the number of clocks to wait after the trigger before beginning to digitize video
    trig.offset = 1600,
    vid.xgain = 15
    ),

  RIB = list ( 
    antenna = "Furuno FR1954C-BB",
    ## bits per sample; this is fixed as 8 
    bps = 8,
    dsp = 7,
    master = TRUE,
    range.index = 3,
    neg.video = TRUE 
    ),
  
  TCPIP = list (
    ## bits per sample; this is fixed as 8 
    bps = 8,
    
    ## active mode?  if FALSE, no server settings can be modified
    active = TRUE,

    ## connection timeout, in seconds
    timeout = 3,

    ## range index
    range.index = 3,

    ## by default, don't negate as this is done at the server end
    ## (TCPIP gets cooked data, USB and RIB get raw data)
    neg.video = FALSE,
    
    ## host login information by hostname
    ## Each entry, tagged with a hostname, is of the form list(username, password)
    ## If password is given as NA, then the user is prompted for
    ## the password at connection time.  For an empty password, specify "".
    
    login.info = list ( 
      LOCALHOST = c("", ""),
      XIR3000C = c("", "") 
      ) 
    ) 
  ) 


## ordered list of scan info items returned by this plugin
scan.info.names = c("pulses", "samples.per.pulse", "bits.per.sample", "timestamp", 
  "duration", "sample.dist", "first.sample.dist", "bearing", "orientation", 
  "PLEN", "PRF") 

## should we get raw or pre-processed data?
## pre-processed uses the video negative, video reference, and video threshold values,
## which reduces the information content.  TCPIP mode always uses cooked data,
## regardless of this flag.

use.raw.data = TRUE 


