## This Makefile is called recursively from the Makefile in the parent directory,
## and requires the variables defined there.  To make this plugin, do 

$(eval $(AT_MAKEFILE_START))

ifeq ($(TARGET_PLATFORM), windows)

COPY_AS_IS = pthreadGC2.dll zlib1.dll

endif

clean: 

$(eval $(AT_MAKEFILE_END))
