## svn $Id: zone.conf.R 574 2010-05-11 02:07:15Z john $
##                                                        
##              ZONE PLUGIN CONFIG                     
##                                                        
##  These are parameters for the plugin "zone".
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it may be overwritten with new values if you choose   
##  to save the configuration when you exit radR.         
##                                                        

## is the plugin enabled upon loading?  If TRUE, then
## the plugin's hook functions are installed and enabled.

enabled = FALSE

## where are zone definitions found?

zones.file = "zones/default.zone.R"

## the style for drawing zones.  If a zone's tag is in
## the list, the corresponding style is used.  Otherwise,
## the "default" style is used.  You can add other styles.

styles = list (

  ## style for the exclusion zone:
  
  exclusion = list (
  
    ## Each item is a character vector; the first element is the
    ## normal style for the item; the second is the "highlighted" style
    ## used to show the active segment.

    arc = c("-width 1", "-outline white"),
    line = c("-width 1", "-fill white"),
    point = c("-width 2", "-outline white"),

    ## the radius of control ("corner") points on segments
    
    radius = 5
  ),

  ## default zone style:
  
  default = list (
    arc = c("-width 1", "-outline white"),
    line = c("-width 1", "-fill white"),
    point = c("-width 2", "-outline white"),
    radius = 5
    )
  )

## the colour of newly created zones

default.new.zone.colour = "blue"

## should data in the exclusion zone be zeroed (and not just classified
## as EXCLUDED)?  Setting this to true allows better compression when
## saving a raw archive.

zero.exclusion = TRUE

