## svn $Id: generic.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##     GENERIC  INTERFACE  CONFIG
##                                                         
##  These are parameters for the generic interface plugin. 
##  This plugin is used to define generic methods for the  
##  the other interface plugins (which define class        
##  methods for their object class)                        
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


enabled = TRUE

## this plugin is always on

always.on = TRUE

## Nothing else is needed here - the plugin's globals item,
## in generic.plugin.R, does all the work.

