## svn $Id: brightprimary.palette.R 214 2009-02-12 16:16:09Z john $
##                                                        
##  bright primary colour rainbow
##                                                        
##  This file defines a palette for radR.                  
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it may be overwritten with new values by radR.
##                                                        
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.            

## a short string describing this palette

desc = "gradient of bright primary colours"

## The vector of points.  These are real values in the range
## 0.0 to 1.0 for which colours will be specified.
## There must be at least one point.

points = (0:6) / 6

## Colours for the points.  This is a character vector of tcl colours
## in the "#RRGGBB" format.
## Colours must be supplied for all points.

colours = c( "#0000ff", "#00ffff", "#00ff00", "#ffff00", "#ff0000", "#ff00ff", "#ffffff" )

## Alpha values for the colours.  These are integers between 0 and 255, with 0 meaning
## completely transparent (regardless of the colour) and 255 meaning completely opaque.

alpha = c( 0xff, 0xff, 0xff, 0xff, 0xff, 0xff, 0xff)

