## svn $Id: greenramp.palette.R 214 2009-02-12 16:16:09Z john $
##                                                        
##  green ramp
##                                                        
##  This file defines a palette for radR.                  
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it may be overwritten with new values by radR.
##                                                        
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.            

## a short string describing this palette

desc = "a green gradient for blip trails"

## The vector of points.  These are real values in the range
## 0.0 to 1.0 for which colours will be specified.
## There must be at least one point.

points = c(0, 1)

## Colours for the points.  This is a character vector of tcl colours
## in the "#RRGGBB" format.
## Colours must be supplied for all points.

colours = c("#000000", "#00ff00")

## Alpha values for the colours.  These are integers between 0 and 255, with 0 meaning
## completely transparent (regardless of the colour) and 255 meaning completely opaque.

alpha = c(0xff, 0xff)
