## svn $Id: blipmoviearch.conf.R 574 2010-05-11 02:07:15Z john $
##
##  BLIPMOVIEARCH  INTERFACE  CONFIG
##
##  These are parameters for the blipmoviearch plugin.
##  This plugin is an interface for reading/writing
##  blipmovie archive files.
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.
##
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.
##
##  Make sure to include a comma at the end of each item
##  in a list.  A list definition should look like this:
##
##     what.ever = list (
##        something = 45,
##        something.else = 55
##     )
##
##  The first and last lines must not have any actual list
##  items on them, and all items must be named
##  (i.e. NAME = THING, instead of just THING)
##


enabled = TRUE
