##  BLIPSQL  PLUGIN  CONFIG
##
##  These are parameters for the radR plugin blipsql
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.
##
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.
##
##  Make sure to include a comma at the end of each item
##  in a list.  A list definition should look like this:
##
##     what.ever = list (
##        something = 45,
##        something.else = 55
##     )
##
##  The first and last lines must not have any actual list
##  items on them, and all items must be named
##  (i.e. NAME = THING, instead of just THING)


## Is this plugin enabled upon loading?

enabled = TRUE

## where blips are saved, by default; this can include a path

blip.filename = "blips.sqlite"

## whether to pop-up a plot of all blips
## when the pause button is hit

plot.on.pause = FALSE

## whether to plot range rings

plot.range.rings = FALSE

## table definitions for the sqlite file

table.defs = c("
CREATE TABLE IF NOT EXISTS blips (
   t REAL NOT NULL,
   x INTEGER NOT NULL,
   y INTEGER NOT NULL,
   z INTEGER NOT NULL,
   ns INTEGER NOT NULL,
   area INTEGER NOT NULL,
   int double NOT NULL,
   max double NOT NULL,
   aspan INTEGER NOT NULL,
   rspan INTEGER NOT NULL,
   perim INTEGER NOT NULL
)
", "
CREATE INDEX IF NOT EXISTS blips_t ON blips(t)
"
)
