##     PNGARCH   PLUGIN   CONFIG
##                                                        
##  Read frames from PNG files.
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it is overwritten with new values when you exit       
##  radR.                                                 


## is this plugin enabled?
enabled = TRUE 

## this plugin is not always on
always.on = FALSE 

## folder we look for data files in (recursively)

folder = "/media/"


