##     PNGARCH   PLUGIN   CONFIG
##
##  Read frames from PNG files.
##
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because
##  it is overwritten with new values when you exit
##  radR.


## is this plugin enabled?
enabled = TRUE

## this plugin is not always on
always.on = FALSE

## folder we look for data files in (recursively)

folder = "/media/"

## Fixed number of pulses resample to for each sweep.
## Each of target.num.pulses slots obtains a copy of
## the pulse with the closest azimuth, or the latest
## such pulse in case of a tie.

target.num.pulses = 4096
