## This Makefile is called recursively from the Makefile in the parent directory,
## and requires the variables defined there.

$(eval $(AT_MAKEFILE_START))
PLUGIN_LIB_EXTRA_OPTIONS=-llz4
$(eval $(AT_MAKEFILE_END))
