## svn $Id: antenna.conf.R 578 2010-05-11 02:36:53Z john $
##                                                        
##  ANTENNA PLUGIN CONFIGURATION
##                                                        
##  These are parameters for the antenna plugin           
##                                                        
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because     
##  it may be overwritten with new values by radR.
##                                                        
##  Lines beginning with "#" and blank lines are preserved
##  but comments at the ends of lines are not.            
##                                                        
##  Make sure to include a comma at the end of each item  
##  in a list.  A list definition should look like this:  
##                                                        
##     what.ever = list (                                 
##        something = 45,                                 
##        something.else = 55                             
##     )                                                  
##                                                        
##  The first and last lines must not have any actual list
##  items on them, and all items must be named            
##  (i.e. NAME = THING, instead of just THING)            

## should the plugin be enabled on load?

enabled = TRUE 

## this flag tells radR the plugin is always on, and that
## no plugin menu entries for enable/disable or load at start time
## should be created.

always.on = TRUE 

## types of antennas

antenna.types = c("dish", "tbar") 

## current file with radar/antenna information

antenna.filename = "antennas/default.antenna.R" 

## in case we can't load the default antenna information, have some sane fallbacks

default.parms = list ( 
  antenna.angle = 0,
  antenna.aperture.h = 3,
  antenna.aperture.v = 3,
  antenna.desc = "default antenna",
  antenna.plugins = list (
    ),
  antenna.type = "dish",
  bearing.offset = 0,
  elevation = 0,
  first.sample.dist = 0,
  latitude = 0,
  longitude = 0,
  rotation.axis = c(0, 90)
  ) 

## should this plugin override any antenna information provided by the
## current source?  One logical item per element of default.parms, in order

override = c(FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE) 

## labels for antenna parameters:

parm.label = list (
  antenna.angle      = "Angle of beam above rotation plane, in degrees",
  antenna.aperture.h = "Horizontal aperture of beam, in degrees",
  antenna.aperture.v = "Vertical aperture of beam, in degrees",
  antenna.desc       = "Description of antenna",
  antenna.plugins    = "Parameters for plugins such as seascan, xenex",
  antenna.type       = "Antenna type",
  bearing.offset     = "Bearing offset in degrees clockwise from N",
  elevation          = "Elevation of radar, in m above sea level",
  first.sample.dist  = "True range of first sample, in metres",
  latitude           = "Latitude of radar, in degrees N",
  longitude          = "Longitude of radar, in degrees E",
  rotation.axis      = "Rotation axis"
  )
