## svn $Id: bliptrails.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##  BLIPTRAILS  PLUGIN  CONFIG
##                                                         
##  These are parameters for the bliptrails plugin         
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## should the plugin be enabled on load?

enabled = FALSE 

## the available storage modes

available.modes = c("last N scans", "storage tube") 

## the currently selected mode
current.mode = "last N scans" 

## default palettes for the "other" class in
## each mode

default.palette = list (
  `last N scans` = "greenramp",
  `storage tube` = "greenramp"
  ) 

## default gammas for the default palettes

default.gamma = list (
  `last N scans` = 2.0,
  `storage tube` = 2.0
  ) 

## the number of scans from which to retain blip data
## (if mode is last.n.scans)

num.scans.kept = 20 

## the fadeout factor for blip data
## Sample data for a retained scan is multiplied by
## this number before every scan in which it is
## displayed.  This number is accurate to
## approximately 3 decimal places.

fadeout = 0.85 

## do we retain score data?

retain.scores = FALSE 

## Functions to format the sample value and score value for retained blips
## The first is for formatting what is actually shown in the floating info window 
## The second is for formatting what is copied to the clipboard.

formatter = list (
  old.value = function(v) sprintf("Trail sample value: %5d", v),
  old.score = function(sc) sprintf("Trail sample score: %6.3f", sc)
  ) 

clipboard.formatter = list ( 
  old.value = function(v) sprintf("%5d\t", v),
  old.score = function(sc) sprintf("%6.3f", sc)
  )

