## This Makefile is called recursively from the Makefile in the parent directory,
## and requires the variables defined there.

$(eval $(AT_MAKEFILE_START))

PLUGIN_LIB_EXTRA_DEPS = $(RADR_INCLUDE_DIR)/patchify.h
PLUGIN_EXTRA_TARGETS = radR.gif
PLUGIN_EXTRA_R_FILES = radR.gif.geom.R

$(eval $(AT_MAKEFILE_END))
