## svn $Id: underlay.conf.R 574 2010-05-11 02:07:15Z john $
##                                                         
##  UNDERLAY  PLUGIN  CONFIG
##                                                         
##  These are parameters for the underlay plugin           
##                                                         
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because      
##  it is overwritten with new values when you exit        
##  radR.                                                  
##                                                         
##  Lines beginning with "#" and blank lines are preserved 
##  but comments at the ends of lines are not.             
##                                                         
##  Make sure to include a comma at the end of each item   
##  in a list.  A list definition should look like this:   
##                                                         
##     what.ever = list (                                  
##        something = 45,                                  
##        something.else = 55                              
##     )                                                   
##                                                         
##  The first and last lines must not have any actual list 
##  items on them, and all items must be named             
##  (i.e. NAME = THING, instead of just THING)             


## should the plugin be enabled on load?

enabled = FALSE

## the current underlay file

image.file = "plugins/underlay/radR.gif"

image.geom = list (
  ## radar location, relative to the image; top-left corner is (0, 0)
  ## y increases downward
  
  centre = c(400, 300),
  
  ## azimuth of the image: angle of the y axis in degrees clockwise
  ## from North:
  
  azimuth = 90,
  
  ## size of a pixel (these are assumed square) in metres
  
  pixel.size = 20,
  
  ## how does the image change when the plot window changes?
  
  track = list (

    ## if the plot window is zoomed, should the image be too?
    mpp = TRUE,
    
    ## if the plot window is panned, should the image be too?
    
    plot.origin = TRUE,
    
    ## if the plot window is rotated, should the image be too?
    
    north.angle = TRUE
    
    )
  )
