## svn $Id: genblips.conf.R 703 2011-01-07 16:33:09Z john $
##                                                           
##   GENBLIPS  INTERFACE  CONFIG
##                                                           
##  These are parameters for the genblips interface plugin.  
##  This plugin is used to define generic methods for the    
##  the other interface plugins (which define class          
##  methods for their object class)                          
##                                                           
##  DO NOT EDIT THIS FILE WHILE RUNNING radR, because        
##  it is overwritten with new values when you exit          
##  radR.                                                    
##                                                           
##  Lines beginning with "#" and blank lines are preserved   
##  but comments at the ends of lines are not.               
##                                                           
##  Make sure to include a comma at the end of each item     
##  in a list.  A list definition should look like this:     
##                                                           
##     what.ever = list (                                    
##        something = 45,                                    
##        something.else = 55                                
##     )                                                     
##                                                           
##  The first and last lines must not have any actual list   
##  items on them, and all items must be named               
##  (i.e. NAME = THING, instead of just THING)               


enabled = TRUE 

## number of consecutive scans for which to generate blips
## Inf means generate until explicitly stopped

num.scans = Inf 

## generate a .CSV file with the true target tracks?

generate.csv.file = FALSE

## should the .CSV file receive all target positions, or just visible ones?

only.export.visible = TRUE

## name of csv file

csv.filename = "truetracks.csv"

### PARAMETERS DESCRIBING THE SCANS

scan.info = list (
  ## pulses per scan

  pulses = 1024,

  ## samples per pulse

  samples.per.pulse = 512,

  ## bits per sample

  bits.per.sample = 12,
  
  ## duration of a scan (milliseconds)

  duration = 2600,

  ## what distance increment each sample represents (metres)

  sample.dist = 5,

  ## distance at which first sample begins (metres)

  first.sample.dist = 0,
  
  ## how many degrees clockwise from north is the first pulse?

  bearing = 0,

  ## rotation direction (either +1 or -1)

  orientation = 1
  ) 

### PARAMETERS DESCRIBING HOW TARGETS/BLIPS ARE PLOTTED

radius = 4 

### PARAMETERS DESCRIBING TARGETS

## maximum number of concurrent targets in dynamic model

target.n.max = 300 

## function returning number of targets to start in this scan
## (called in each scan); called with scan number

target.new.mu = 5

target.num.new = expression(2 + rpois(1, target.new.mu)) 

## function returning radar cross sections for n target blips

target.rcs.mu = 7 

target.rcs = expression(2 + rpois(n, target.rcs.mu)) 

## function returning start locations for n targets
## this should be a 3xn matrix, with locations in metres
## east of, north of, and above the radar
## These targets are deliberately started outside of the radar's range so that only full
## tracks are generated

target.x0 = expression({r <- max.range + runif(n, 0, max.range); theta <- runif(n, 0, 2*pi); z <- runif(n, 0, 2*max.range); cbind(r*cos(theta), r*sin(theta), z)})

## function returning initial velocities for n targets
## this should be a 3xn matrix, with component velocities in metres/scan
## to the east, to the north, and up

target.v0 = expression(cbind((runif(n)*max.range - max.range / 2) / 30, (runif(n)*max.range - max.range / 2) / 30, (runif(n)*max.range - max.range / 2) / 60))

## function returning accelerations for n targets
## this should be a 3xn matrix, with component accelerations in metres/scan
## to the east, to the north, and up

target.a0 = expression(matrix(0, n, 3))

## decay for the acceleration; acceleration vector is multiplied
## by this scalar (or vector) each scan

target.accel.decay = 0.85 

## maximum speed of a target (km/h)

target.max.speed = 150 

### PARAMETERS DESCRIBING NOISE

## function returning number of noise blips to add to this
## scan

noise.blips.mu = 0 

noise.num.blips = expression(rpois(1, noise.blips.mu)) 

## function returning radar cross section for n noise blips

noise.rcs.mu = 4 

noise.rcs = expression(rpois(n, noise.rcs.mu)) 

## function returning locations for n noise blips
## this should be a 3xn matrix, with locations in metres
## east of, north of, and above the radar

noise.x0 = expression(cbind(matrix(runif(2*n, 0, 2 * max.range) - max.range, nrow=n, ncol=2), runif(n, 0, max.range / 10)))
